//  copyright lexilogos.com
var car;

function transcrire() {
car = document.conversion.saisie.value;
car = car.replace(/ʷ/g, "ᵛ");
 car = car.replace(/a/g, "𐬀");
car = car.replace(/ā/g, "𐬁");
car = car.replace(/𐬀=/g, "𐬁");
car = car.replace(/å/g, "𐬂");
car = car.replace(/𐬁=/g, "𐬂");
car = car.replace(/å/g, "𐬃");
car = car.replace(/𐬂=/g, "𐬃");
car = car.replace(/[ąA]/g, "𐬄");
car = car.replace(/𐬃=/g, "𐬄");
car = car.replace(/ą̇/g, "𐬅");
car = car.replace(/𐬄=/g, "𐬅");
car = car.replace(/𐬅=/g, "𐬀");
car = car.replace(/[əE]/g, "𐬆");
car = car.replace(/ə̄/g, "𐬇");
car = car.replace(/e/g, "𐬈");
car = car.replace(/ē/g, "𐬉");
car = car.replace(/𐬈=/g, "𐬉");
car = car.replace(/𐬉=/g, "𐬆");
car = car.replace(/𐬆=/g, "𐬇");
car = car.replace(/𐬇=/g, "𐬈");
car = car.replace(/o/g, "𐬊");
car = car.replace(/ō/g, "𐬋");
car = car.replace(/𐬊=/g, "𐬋");
car = car.replace(/𐬋=/g, "𐬊");
car = car.replace(/i/g, "𐬌");
car = car.replace(/ī/g, "𐬍");
car = car.replace(/𐬌=/g, "𐬍");
car = car.replace(/𐬍=/g, "𐬌");
car = car.replace(/u/g, "𐬎");
car = car.replace(/ū/g, "𐬏");
car = car.replace(/𐬎=/g, "𐬏");
car = car.replace(/𐬏=/g, "𐬎");
car = car.replace(/k/g, "𐬐");
car = car.replace(/x/g, "𐬑");
car = car.replace(/x́/g, "𐬒");
car = car.replace(/𐬑=/g, "𐬒");
car = car.replace(/xᵛ/g, "𐬓");
car = car.replace(/𐬒=/g, "𐬓");
car = car.replace(/𐬓=/g, "𐬑");
car = car.replace(/g/g, "𐬔");
car = car.replace(/ġ/g, "𐬕");
car = car.replace(/𐬔=/g, "𐬕");
car = car.replace(/[γG]/g, "𐬖");
car = car.replace(/𐬕=/g, "𐬖");
car = car.replace(/𐬖=/g, "𐬔");
car = car.replace(/[cč]/g, "𐬗");
car = car.replace(/[jǰ]/g, "𐬘");
car = car.replace(/t/g, "𐬙");
car = car.replace(/[ϑθ]/g, "𐬚");
car = car.replace(/𐬙=/g, "𐬚");
car = car.replace(/d/g, "𐬛");
car = car.replace(/δ/g, "𐬜");
car = car.replace(/𐬛=/g, "𐬜");
car = car.replace(/𐬜=/g, "𐬛");
car = car.replace(/[Tt̰]/g, "𐬝");
car = car.replace(/𐬚=/g, "𐬝");
car = car.replace(/𐬝=/g, "𐬙");
car = car.replace(/p/g, "𐬞");
car = car.replace(/f/g, "𐬟");
car = car.replace(/b/g, "𐬠");
car = car.replace(/[Bβ]/g, "𐬡");
car = car.replace(/𐬠=/g, "𐬡");
car = car.replace(/𐬡=/g, "𐬠");
car = car.replace(/[Nŋ]/g, "𐬢");
car = car.replace(/𐬧=/g, "𐬢");
car = car.replace(/ŋ́/g, "𐬣");
car = car.replace(/𐬢=/g, "𐬣");
car = car.replace(/ŋᵛ/g, "𐬤");
car = car.replace(/𐬣=/g, "𐬤");
car = car.replace(/n/g, "𐬥");
car = car.replace(/ń/g, "𐬦");
car = car.replace(/𐬥=/g, "𐬦");
car = car.replace(/ṇ/g, "𐬧");
car = car.replace(/𐬦=/g, "𐬧");
car = car.replace(/𐬤=/g, "𐬥");
car = car.replace(/m/g, "𐬨");
car = car.replace(/m̨/g, "𐬩");
car = car.replace(/𐬨=/g, "𐬩");
car = car.replace(/𐬩=/g, "𐬨");
car = car.replace(/[Yẏ]/g, "𐬪");
car = car.replace(/y/g, "𐬫");
car = car.replace(/𐬫=/g, "𐬪");
car = car.replace(/𐬪=/g, "𐬫");
car = car.replace(/v/g, "𐬬");
car = car.replace(/r/g, "𐬭");
car = car.replace(/l/g, "𐬮");
car = car.replace(/s/g, "𐬯");
car = car.replace(/z/g, "𐬰");
car = car.replace(/š/g, "𐬱");
car = car.replace(/𐬯=/g, "𐬱");
car = car.replace(/ž/g, "𐬲");
car = car.replace(/𐬰=/g, "𐬲");
car = car.replace(/[Sš́]/g, "𐬳");
car = car.replace(/𐬱=/g, "𐬳");
car = car.replace(/ṣ̌/g, "𐬴");
car = car.replace(/𐬳=/g, "𐬴");
car = car.replace(/𐬴=/g, "𐬯");
car = car.replace(/h/g, "𐬵");

startPos = document.conversion.saisie.selectionStart;
endPos = document.conversion.saisie.selectionEnd;

beforeLen = document.conversion.saisie.value.length;
afterLen = car.length;
adjustment = afterLen - beforeLen;

document.conversion.saisie.value = car;

document.conversion.saisie.selectionStart = startPos + adjustment;
document.conversion.saisie.selectionEnd = endPos + adjustment;

var obj = document.conversion.saisie;
obj.focus();
obj.scrollTop = obj.scrollHeight;
}