//  copyright lexilogos.com
var car;

function transcrire() {
car = document.conversion.saisie.value;
car = car.replace(/’/g, "\'");
car = car.replace(/a/g, "ا");
car = car.replace(/اا/g, "آ");
car = car.replace(/[āâ]/g, "آ");
car = car.replace(/A/g, "ٔ");
car = car.replace(/[ạẠ]]/g, "ٔ");
car = car.replace(/ٔٔ/g, "ٲ");
car = car.replace(/ạ̄/g, "ٲ");
car = car.replace(/Ạ̄/g, "ٲ");
car = car.replace(/w/g, "َ");
car = car.replace(/ََ/g, "آ");

car = car.replace(/b/g, "ب");
car = car.replace(/ب'/g, "پ");
car = car.replace(/p/g, "پ");
car = car.replace(/t/g, "ت");
car = car.replace(/ت'/g, "ث");
car = car.replace(/تت/g, "ٹ");
car = car.replace(/ṭ/g, "ٹ");
car = car.replace(/j/g, "ج");
car = car.replace(/c/g, "چ");
car = car.replace(/ج'/g, "چ");
car = car.replace(/H/g, "ح");
car = car.replace(/ح'/g, "خ");
car = car.replace(/x/g, "خ");
car = car.replace(/K/g, "خ");
car = car.replace(/d/g, "د");
car = car.replace(/د'/g, "ذ");
car = car.replace(/دد/g, "ڈ");
car = car.replace(/ḍ/g, "ڈ");
car = car.replace(/r/g, "ر");
car = car.replace(/z/g, "ز");
car = car.replace(/ر'/g, "ز");
car = car.replace(/ز'/g, "ژ");
car = car.replace(/رر/g, "ڑ");
car = car.replace(/ṛ/g, "ڑ");
car = car.replace(/s/g, "س");
car = car.replace(/س'/g, "ش");
car = car.replace(/S/g, "ص");
car = car.replace(/ص'/g, "ض");
car = car.replace(/D/g, "ض");
car = car.replace(/T/g, "ط");
car = car.replace(/ط'/g, "ظ");
car = car.replace(/[ZŻż]/g, "ظ");
car = car.replace(/G/g, "ع");
car = car.replace(/ع'/g, "غ");
car = car.replace(/ğ/g, "غ");
car = car.replace(/f/g, "ف");
car = car.replace(/q/g, "ق");
car = car.replace(/k/g, "ک");
car = car.replace(/ک'/g, "گ");
car = car.replace(/g/g, "گ");
car = car.replace(/l/g, "ل");
car = car.replace(/m/g, "م");
car = car.replace(/n/g, "ن");
car = car.replace(/[NṄṅ]/g, "ں");
car = car.replace(/h/g, "ہ");
car = car.replace(/ہ'/g, "ھ");
car = car.replace(/ھ'/g, "ہ");

car = car.replace(/e/g, "ے");
car = car.replace(/u/g, "ُ");
car = car.replace(/ū/g, "ُ");
car = car.replace(/ُُ/g, "وٗ");
car = car.replace(/U/g, "");
car = car.replace(/Ū/g, "");
car = car.replace(/ﺇﺇ/g, "ٳ");
car = car.replace(/اُ'/g, "ﺇ");
car = car.replace(/ﺇ'/g, "ٳ");
car = car.replace(/ٳ'/g, "اُ");
car = car.replace(/o/g, "ۆ");
car = car.replace(/[ōv]/g, "و");
car = car.replace(/ۆۆ/g, "و");
car = car.replace(/O/g, "ۄ");
car = car.replace(/Ō/g, "ۄآ");
car = car.replace(/ۄۄ/g, "ۄآ");
car = car.replace(/i/g, "ِ");
car = car.replace(/ī/g, "ی");
car = car.replace(/ِِ/g, "ی");
car = car.replace(/y/g, "ؠ");  // bul
// car  = car.replace(/ی'/g, "ي");
car = car.replace(/-/g, "ء");
car = car.replace(/\?/g, "؟");
car = car.replace(/;/g, "؛");
car = car.replace(/,/g, "،");
car = car.replace(/0/g, "۰");
car = car.replace(/1/g, "۱");
car = car.replace(/2/g, "۲");
car = car.replace(/3/g, "۳");
car = car.replace(/4/g, "۴");
car = car.replace(/5/g, "۵");
car = car.replace(/6/g, "۶");
car = car.replace(/7/g, "۷");
car = car.replace(/8/g, "۸");
car = car.replace(/9/g, "۹");
car = car.replace(/\//g, "\u200c");

car = car.replace(/श/g, "ش");
car = car.replace(/स/g, "س");
car = car.replace(/झ़/g, "ژ");
car = car.replace(/ज़/g, "ز");
car = car.replace(/ड़/g, "ڑ");
car = car.replace(/र/g, "ر");
car = car.replace(/ज़ /g, "ذ");
car = car.replace(/ड/g, "ڈ");
car = car.replace(/द/g, "د");
car = car.replace(/ख़/g, "خ");
car = car.replace(/ह/g, "ح");
car = car.replace(/च/g, "چ");
car = car.replace(/ज/g, "ج");
car = car.replace(/स/g, "ث");
car = car.replace(/ट/g, "ٹ");
car = car.replace(/त/g, "ت");
car = car.replace(/प/g, "پ");
car = car.replace(/ब/g, "ب");
car = car.replace(/आ/g, "آ");
car = car.replace(/ए/g, "ے");
car = car.replace(/य/g, "ی");
car = car.replace(/ह/g, "ه");
car = car.replace(/व/g, "و");
car = car.replace(/ङ/g, "ں");
car = car.replace(/न/g, "ن");
car = car.replace(/म/g, "م");
car = car.replace(/ल/g, "ل");
car = car.replace(/ग/g, "گ");
car = car.replace(/क/g, "ک");
car = car.replace(/क़/g, "ق");
car = car.replace(/फ़/g, "ف");
car = car.replace(/ग़/g, "غ");
car = car.replace(/ज़/g, "ظ");
car = car.replace(/त/g, "ط");
car = car.replace(/ज़/g, "ض");
car = car.replace(/स/g, "ص");


startPos = document.conversion.saisie.selectionStart;
endPos = document.conversion.saisie.selectionEnd;

beforeLen = document.conversion.saisie.value.length;
afterLen = car.length;
adjustment = afterLen - beforeLen;

document.conversion.saisie.value = car;

document.conversion.saisie.selectionStart = startPos + adjustment;
document.conversion.saisie.selectionEnd = endPos + adjustment;

var obj = document.conversion.saisie;
obj.focus();
obj.scrollTop = obj.scrollHeight;
}