//  copyright lexilogos.com
var car;

function transcrire() {
car = document.conversion.saisie.value;
car = car.replace(/a/g, "а");
car = car.replace(/а=/g, "ә");
car = car.replace(/ä/g, "ә");
car = car.replace(/ә=/g, "я");
car = car.replace(/я=/g, "а");
car = car.replace(/b/g, "б");
car = car.replace(/v/g, "в");
car = car.replace(/g/g, "г");
car = car.replace(/г=/g, "ғ");
car = car.replace(/ğ/g, "ғ");
car = car.replace(/ғ=/g, "г");
car = car.replace(/d/g, "д");
car = car.replace(/e/g, "е");
car = car.replace(/е=/g, "ё");
car = car.replace(/ë/g, "ё");
car = car.replace(/ё=/g, "э");
car = car.replace(/é/g, "э");
car = car.replace(/э=/g, "е");
car = car.replace(/j/g, "ж");
car = car.replace(/z/g, "з");
car = car.replace(/i/g, "і");
car = car.replace(/і=/g, "и");
car = car.replace(/ï/g, "и");
car = car.replace(/и=/g, "і");
car = car.replace(/y/g, "й");
car = car.replace(/k/g, "к");
car = car.replace(/к=/g, "қ");
car = car.replace(/q/g, "қ");
car = car.replace(/қ=/g, "к");
car = car.replace(/l/g, "л");
car = car.replace(/m/g, "м");
car = car.replace(/n/g, "н");
car = car.replace(/н=/g, "ң");
car = car.replace(/[ŋñ]/g, "ң");
car = car.replace(/ң=/g, "н");
car = car.replace(/o/g, "о");
car = car.replace(/о=/g, "ө");
car = car.replace(/ö/g, "ө");
car = car.replace(/ө=/g, "о");
car = car.replace(/p/g, "п");
car = car.replace(/r/g, "р");
car = car.replace(/s/g, "с");
car = car.replace(/t/g, "т");
car = car.replace(/w/g, "у");
car = car.replace(/u/g, "ұ");
car = car.replace(/ұ=/g, "ү");
car = car.replace(/ү=/g, "ю");
car = car.replace(/ü/g, "ү");
car = car.replace(/ю=/g, "ұ");
car = car.replace(/f/g, "ф");
car = car.replace(/x/g, "х");
car = car.replace(/h/g, "һ");
car = car.replace(/c/g, "ц");
car = car.replace(/ц=/g, "ч");
car = car.replace(/ç/g, "ч");
car = car.replace(/ч=/g, "ц");
car = car.replace(/ş/g, "ш");
car = car.replace(/с=/g, "ш");
car = car.replace(/ш=/g, "с");
car = car.replace(/шч/g, "щ");
car = car.replace(/ı/g, "ы");
car = car.replace(/й=/g, "ы");
car = car.replace(/ы=/g, "й");
car = car.replace(/йй/g, "ы"); // ajout
car = car.replace(/’/g, "ь"); //var
car = car.replace(/'/g, "ь"); //var
car = car.replace(/ʹ/g, "ь");
car = car.replace(/ʺ/g, "ъ");
car = car.replace(/ьь/g, "ъ");
//car = car.replace(/йұ/g, "ю");
//car = car.replace(/йа/g, "я");
//car = car.replace(/йо/g, "ё");
car = car.replace(/û/g, "ю");
car = car.replace(/â/g, "я");

car = car.replace(/A/g, "А");
car = car.replace(/А=/g, "Ә");
car = car.replace(/Ä/g, "Ә");
car = car.replace(/Ә=/g, "Я");
car = car.replace(/Я=/g, "А");
car = car.replace(/B/g, "Б");
car = car.replace(/V/g, "В");
car = car.replace(/G/g, "Г");
car = car.replace(/Г=/g, "Ғ");
car = car.replace(/Ğ/g, "Ғ");
car = car.replace(/Ғ=/g, "Г");
car = car.replace(/D/g, "Д");
car = car.replace(/E/g, "Е");
car = car.replace(/Е=/g, "Ё");
car = car.replace(/Ë/g, "Ё");
car = car.replace(/Ё=/g, "Э");
car = car.replace(/É/g, "Э");
car = car.replace(/Э=/g, "Е");
car = car.replace(/J/g, "Ж");
car = car.replace(/Z/g, "З");
car = car.replace(/I/g, "І");
car = car.replace(/І=/g, "И");
car = car.replace(/Ï/g, "И");
car = car.replace(/И=/g, "І");
car = car.replace(/Y/g, "Й");
car = car.replace(/K/g, "К");
car = car.replace(/К=/g, "Қ");
car = car.replace(/Q/g, "Қ");
car = car.replace(/Қ=/g, "К");
car = car.replace(/L/g, "Л");
car = car.replace(/M/g, "М");
car = car.replace(/N/g, "Н");
car = car.replace(/Н=/g, "Ң");
car = car.replace(/[ŊÑ]/g, "Ң");
car = car.replace(/Ң=/g, "Н");
car = car.replace(/O/g, "О");
car = car.replace(/О=/g, "Ө");
car = car.replace(/Ö/g, "Ө");
car = car.replace(/Ө=/g, "О");
car = car.replace(/P/g, "П");
car = car.replace(/R/g, "Р");
car = car.replace(/S/g, "С");
car = car.replace(/T/g, "Т");
car = car.replace(/W/g, "У");
car = car.replace(/U/g, "Ұ");
car = car.replace(/Ұ=/g, "Ү");
car = car.replace(/Ü/g, "Ү");
car = car.replace(/Ү=/g, "Ю");
car = car.replace(/Ю=/g, "Ұ");
car = car.replace(/F/g, "Ф");
car = car.replace(/X/g, "Х");
car = car.replace(/H/g, "Һ");
car = car.replace(/C/g, "Ц");
car = car.replace(/Ц=/g, "Ч");
car = car.replace(/Ç/g, "Ч");
car = car.replace(/Ч=/g, "Ц");
car = car.replace(/Ş/g, "Ш");
car = car.replace(/С=/g, "Ш");
car = car.replace(/Ш=/g, "С");
car = car.replace(/ШЧ/g, "Щ");
car = car.replace(/I/g, "Ы");
car = car.replace(/Й=/g, "Ы");
car = car.replace(/Ы=/g, "Й");
car = car.replace(/ЙЙ/g, "Ы"); // ajout
//car = car.replace(/ЙҰ/g, "Ю");
//car = car.replace(/ЙА/g, "Я");
//car = car.replace(/ЙО/g, "Ё");
//car = car.replace(/Йұ/g, "Ю");
//car = car.replace(/Йа/g, "Я");
//car = car.replace(/Йо/g, "Ё");
car = car.replace(/Û/g, "Ю");
car = car.replace(/Â/g, "Я");

startPos = document.conversion.saisie.selectionStart;
endPos = document.conversion.saisie.selectionEnd;

beforeLen = document.conversion.saisie.value.length;
afterLen = car.length;
adjustment = afterLen - beforeLen;

document.conversion.saisie.value = car;

document.conversion.saisie.selectionStart = startPos + adjustment;
document.conversion.saisie.selectionEnd = endPos + adjustment;

var obj = document.conversion.saisie;
obj.focus();
obj.scrollTop = obj.scrollHeight;
}