//  copyright lexilogos.com
var car;

function transcrire() {
car = document.conversion.saisie.value;
car = car.replace(/a=/g, "á");
car = car.replace(/á=/g, "à");
car = car.replace(/à=/g, "â");
car = car.replace(/â=/g, "ā");
car = car.replace(/ā=/g, "ä");
car = car.replace(/ä=/g, "ã");
car = car.replace(/ã=/g, "å");
car = car.replace(/å=/g, "æ");
car = car.replace(/æ=/g, "ă");
car = car.replace(/ă=/g, "ą");
car = car.replace(/ą=/g, "a");
car = car.replace(/e=/g, "é");
car = car.replace(/é=/g, "è");
car = car.replace(/è=/g, "ê");
car = car.replace(/ê=/g, "ē");
car = car.replace(/ē=/g, "ë");
car = car.replace(/ë=/g, "ě");
car = car.replace(/ě=/g, "ė");
car = car.replace(/ė=/g, "ę");
car = car.replace(/ę=/g, "e");
car = car.replace(/i=/g, "í");
car = car.replace(/í=/g, "ì");
car = car.replace(/ì=/g, "î");
car = car.replace(/î=/g, "ī");
car = car.replace(/ī=/g, "ï");
car = car.replace(/ï=/g, "į");
car = car.replace(/į=/g, "ı");
car = car.replace(/ı=/g, "i");
car = car.replace(/ï=/g, "i");
car = car.replace(/o=/g, "ó");
car = car.replace(/ó=/g, "ò");
car = car.replace(/ò=/g, "ô");
car = car.replace(/ô=/g, "ō");
car = car.replace(/ō=/g, "ö");
car = car.replace(/ö=/g, "õ");
car = car.replace(/õ=/g, "ø");
car = car.replace(/ø=/g, "œ");
car = car.replace(/œ=/g, "ő");
car = car.replace(/ő=/g, "o");
car = car.replace(/u=/g, "ú");
car = car.replace(/ú=/g, "ù");
car = car.replace(/ù=/g, "û");
car = car.replace(/û=/g, "ū");
car = car.replace(/ū=/g, "ü");
car = car.replace(/ü=/g, "ű");
car = car.replace(/ű=/g, "ų");
car = car.replace(/ų=/g, "ů");
car = car.replace(/ů=/g, "u");
car = car.replace(/w=/g, "ŵ");
car = car.replace(/ŵ=/g, "w");
car = car.replace(/y=/g, "ý");
car = car.replace(/ý=/g, "ŷ");
car = car.replace(/ŷ=/g, "ȳ");
car = car.replace(/ȳ=/g, "ÿ");
car = car.replace(/ÿ=/g, "y");
car = car.replace(/c=/g, "ç");
car = car.replace(/ç=/g, "ć");
car = car.replace(/ć=/g, "č");
car = car.replace(/č=/g, "c");
car = car.replace(/d=/g, "ď");
car = car.replace(/ď=/g, "đ");
car = car.replace(/đ=/g, "ð");
car = car.replace(/ð=/g, "d");
car = car.replace(/t=/g, "ť");
car = car.replace(/ť=/g, "þ");
car = car.replace(/þ=/g, "t");
car = car.replace(/n=/g, "ñ");
car = car.replace(/ñ=/g, "ń");
car = car.replace(/ń=/g, "ň");
car = car.replace(/ň=/g, "n");
car = car.replace(/r=/g, "ŕ");
car = car.replace(/ŕ=/g, "ř");
car = car.replace(/ř=/g, "r");
car = car.replace(/s=/g, "ś");
car = car.replace(/ś=/g, "š");
car = car.replace(/š=/g, "ß");
car = car.replace(/ß=/g, "s");
car = car.replace(/z=/g, "ź");
car = car.replace(/ź=/g, "ž");
car = car.replace(/ž=/g, "ż");
car = car.replace(/ż=/g, "z");
car = car.replace(/l=/g, "ł");
car = car.replace(/ł=/g, "ĺ");
car = car.replace(/ĺ=/g, "ľ");
car = car.replace(/ľ=/g, "l");

car = car.replace(/A=/g, "Á");
car = car.replace(/Á=/g, "À");
car = car.replace(/À=/g, "Â");
car = car.replace(/Â=/g, "Ā");
car = car.replace(/Ā=/g, "Ä");
car = car.replace(/Ä=/g, "Ã");
car = car.replace(/Ã=/g, "Å");
car = car.replace(/Å=/g, "Æ");
car = car.replace(/Æ=/g, "Ă");
car = car.replace(/Ă=/g, "Ą");
car = car.replace(/Ą=/g, "A");
car = car.replace(/E=/g, "É");
car = car.replace(/É=/g, "È");
car = car.replace(/È=/g, "Ê");
car = car.replace(/Ê=/g, "Ē");
car = car.replace(/Ē=/g, "Ë");
car = car.replace(/Ë=/g, "Ě");
car = car.replace(/Ě=/g, "Ė");
car = car.replace(/Ė=/g, "Ę");
car = car.replace(/Ę=/g, "E");
car = car.replace(/I=/g, "Í");
car = car.replace(/Í=/g, "Ì");
car = car.replace(/Ì=/g, "Î");
car = car.replace(/Î=/g, "Ī");
car = car.replace(/Ī=/g, "Ï");
car = car.replace(/Ï=/g, "Į");
car = car.replace(/Į=/g, "ı");
car = car.replace(/ı=/g, "I");
car = car.replace(/Ï=/g, "I");
car = car.replace(/O=/g, "Ó");
car = car.replace(/Ó=/g, "Ò");
car = car.replace(/Ò=/g, "Ô");
car = car.replace(/Ô=/g, "Ō");
car = car.replace(/Ō=/g, "Ö");
car = car.replace(/Ö=/g, "Õ");
car = car.replace(/Õ=/g, "Ø");
car = car.replace(/Ø=/g, "Œ");
car = car.replace(/Œ=/g, "Ő");
car = car.replace(/Ő=/g, "O");
car = car.replace(/U=/g, "Ú");
car = car.replace(/Ú=/g, "Ù");
car = car.replace(/Ù=/g, "Û");
car = car.replace(/Û=/g, "Ū");
car = car.replace(/Ū=/g, "Ü");
car = car.replace(/Ü=/g, "Ű");
car = car.replace(/Ű=/g, "Ų");
car = car.replace(/Ų=/g, "Ů");
car = car.replace(/Ů=/g, "U");
car = car.replace(/W=/g, "Ŵ");
car = car.replace(/Ŵ=/g, "W");
car = car.replace(/Y=/g, "Ý");
car = car.replace(/Ý=/g, "Ŷ");
car = car.replace(/Ŷ=/g, "Ȳ");
car = car.replace(/Ȳ=/g, "Ÿ");
car = car.replace(/Ÿ=/g, "Y");
car = car.replace(/C=/g, "Ç");
car = car.replace(/Ç=/g, "Ć");
car = car.replace(/Ć=/g, "Č");
car = car.replace(/Č=/g, "C");
car = car.replace(/D=/g, "Ď");
car = car.replace(/Ď=/g, "Đ");
car = car.replace(/Đ=/g, "Ð");
car = car.replace(/Ð=/g, "D");
car = car.replace(/T=/g, "Ť");
car = car.replace(/Ť=/g, "Þ");
car = car.replace(/Þ=/g, "T");
car = car.replace(/N=/g, "Ñ");
car = car.replace(/Ñ=/g, "Ń");
car = car.replace(/Ń=/g, "Ň");
car = car.replace(/Ň=/g, "N");
car = car.replace(/R=/g, "Ŕ");
car = car.replace(/Ŕ=/g, "Ř");
car = car.replace(/Ř=/g, "R");
car = car.replace(/S=/g, "Ś");
car = car.replace(/Ś=/g, "Š");
car = car.replace(/Š=/g, "ẞ");
car = car.replace(/ẞ=/g, "S");
car = car.replace(/Z=/g, "Ź");
car = car.replace(/Ź=/g, "Ž");
car = car.replace(/Ž=/g, "Ż");
car = car.replace(/Ż=/g, "Z");
car = car.replace(/L=/g, "Ł");
car = car.replace(/Ł=/g, "Ĺ");
car = car.replace(/Ĺ=/g, "Ľ");
car = car.replace(/Ľ=/g, "L");

car = car.replace(/\?=/g, "¿");
car = car.replace(/\!=/g, "¡");

startPos = document.conversion.saisie.selectionStart;
endPos = document.conversion.saisie.selectionEnd;

beforeLen = document.conversion.saisie.value.length;
afterLen = car.length;
adjustment = afterLen - beforeLen;

document.conversion.saisie.value = car;

document.conversion.saisie.selectionStart = startPos + adjustment;
document.conversion.saisie.selectionEnd = endPos + adjustment;

var obj = document.conversion.saisie;
obj.focus();
obj.scrollTop = obj.scrollHeight;
}