//copyright lexilogos.com
var car;

function transcrire() {
car = document.conversion.saisie.value;
car = car.replace(/h/g, "х");
car = car.replace(/j/g, "ј");
car = car.replace(/c/g, "ц");
car = car.replace(/a/g, "а");
car = car.replace(/b/g, "б");
car = car.replace(/v/g, "в");
car = car.replace(/g/g, "г");
car = car.replace(/d/g, "д");
car = car.replace(/e/g, "е");
car = car.replace(/д=/g, "ђ");
car = car.replace(/д-/g, "ђ");
car = car.replace(/ђ=/g, "д");
car = car.replace(/z/g, "з");
car = car.replace(/з=/g, "ж");
car = car.replace(/ж=/g, "з");
car = car.replace(/зх/g, "ж");
car = car.replace(/i/g, "и");
car = car.replace(/k/g, "к");
car = car.replace(/l/g, "л");
car = car.replace(/л=/g, "љ");
car = car.replace(/лј/g, "љ");
car = car.replace(/m/g, "м");
car = car.replace(/n/g, "н");
car = car.replace(/н=/g, "њ");
car = car.replace(/нј/g, "њ");
car = car.replace(/o/g, "о");
car = car.replace(/p/g, "п");
car = car.replace(/r/g, "р");
car = car.replace(/s/g, "с");
car = car.replace(/t/g, "т");
car = car.replace(/т=/g, "ћ");
car = car.replace(/ћ=/g, "ц");
car = car.replace(/цј/g, "ћ");
car = car.replace(/ц'/g, "ћ");
car = car.replace(/u/g, "у");
car = car.replace(/f/g, "ф");
car = car.replace(/цх/g, "ч");
car = car.replace(/ц=/g, "ч");
car = car.replace(/ч=/g, "ћ");
car = car.replace(/дж/g, "џ");
car = car.replace(/с=/g, "ш");
car = car.replace(/ш=/g, "с");
car = car.replace(/сх/g, "ш");
car = car.replace(/H/g, "Х");
car = car.replace(/J/g, "Ј");
car = car.replace(/C/g, "Ц");
car = car.replace(/A/g, "А");
car = car.replace(/B/g, "Б");
car = car.replace(/V/g, "В");
car = car.replace(/G/g, "Г");
car = car.replace(/D/g, "Д");
car = car.replace(/E/g, "Е");
car = car.replace(/Д=/g, "Ђ");
car = car.replace(/Д-/g, "Ђ");
car = car.replace(/Ђ=/g, "Д");
car = car.replace(/Z/g, "З");
car = car.replace(/З=/g, "Ж");
car = car.replace(/Ж=/g, "З");
car = car.replace(/ЗХ/g, "Ж");
car = car.replace(/Зх/g, "Ж");
car = car.replace(/I/g, "И");
car = car.replace(/K/g, "К");
car = car.replace(/L/g, "Л");
car = car.replace(/Л=/g, "Љ");
car = car.replace(/ЛЈ/g, "Љ");
car = car.replace(/Лј/g, "Љ");
car = car.replace(/M/g, "М");
car = car.replace(/N/g, "Н");
car = car.replace(/Н=/g, "Њ");
car = car.replace(/НЈ/g, "Њ");
car = car.replace(/Нј/g, "Њ");
car = car.replace(/O/g, "О");
car = car.replace(/P/g, "П");
car = car.replace(/R/g, "Р");
car = car.replace(/S/g, "С");
car = car.replace(/T/g, "Т");
car = car.replace(/Т=/g, "Ћ");
car = car.replace(/Ч=/g, "Ћ");
car = car.replace(/Ћ=/g, "Ц");
car = car.replace(/ЦЈ/g, "Ћ");
car = car.replace(/Цј/g, "Ћ");
car = car.replace(/Ц'/g, "Ћ");
car = car.replace(/U/g, "У");
car = car.replace(/F/g, "Ф");
car = car.replace(/ЦХ/g, "Ч");
car = car.replace(/Цх/g, "Ч");
car = car.replace(/Ц=/g, "Ч");
car = car.replace(/ДЖ/g, "Џ");
car = car.replace(/Дж/g, "Џ");
car = car.replace(/С=/g, "Ш");
car = car.replace(/Ш=/g, "С");
car = car.replace(/СХ/g, "Ш");
car = car.replace(/Сх/g, "Ш");
car = car.replace(/đ/g, "ђ");
car = car.replace(/ž/g, "ж");
car = car.replace(/ć/g, "ћ");
car = car.replace(/č/g, "ч");
car = car.replace(/š/g, "ш");
car = car.replace(/Đ/g, "Ђ");
car = car.replace(/Ž/g, "Ж");
car = car.replace(/Ć/g, "Ћ");
car = car.replace(/Č/g, "Ч");
car = car.replace(/Š/g, "Ш");

startPos = document.conversion.saisie.selectionStart;
endPos = document.conversion.saisie.selectionEnd;

beforeLen = document.conversion.saisie.value.length;
afterLen = car.length;
adjustment = afterLen - beforeLen;

document.conversion.saisie.value = car;

document.conversion.saisie.selectionStart = startPos + adjustment;
document.conversion.saisie.selectionEnd = endPos + adjustment;

var obj = document.conversion.saisie;
obj.focus();
obj.scrollTop = obj.scrollHeight;
}