//  copyright lexilogos.com
var car;

function latmor() {
    car = document.transcription.text1.value.toUpperCase();
    car = car.replace(/Ê/g, "E");
    car = car.replace(/Ë/g, "E");
    car = car.replace(/Â/g, "A");
    car = car.replace(/Á/g, "A");
    car = car.replace(/Ô/g, "O");
    car = car.replace(/Ó/g, "O");
    car = car.replace(/Ò/g, "O");
    car = car.replace(/Î/g, "I");
    car = car.replace(/Ï/g, "I");
    car = car.replace(/Ì/g, "I");
    car = car.replace(/Í/g, "I");
    car = car.replace(/Ù/g, "U");
    car = car.replace(/Û/g, "U");
    car = car.replace(/Ú/g, "U");
    car = car.replace(/Ÿ/g, "Y");
    car = car.replace(/Œ/g, "OE");
    car = car.replace(/«/g, "\"");
    car = car.replace(/»/g, "\"");
    car = car.replace(/’/g, "\'");

    car = car.replace(/\'/g, "·−−−−· ");
    car = car.replace(/\-/g, "−····− ");
    car = car.replace(/\!/g, "−·−·−− ");
    car = car.replace(/\&/g, "·−··· ");
    car = car.replace(/\"/g, "·−··−· ");
    car = car.replace(/\(/g, "−·−−· ");
    car = car.replace(/\)/g, "−·−−·− ");
    car = car.replace(/\,/g, "−−··−− ");
    car = car.replace(/\./g, "·−·−·− ");
    car = car.replace(/\//g, "−··−· ");
    car = car.replace(/\:/g, "−−−··· ");
    car = car.replace(/\;/g, "−·−·−· ");
    car = car.replace(/\?/g, "··−−·· ");
    car = car.replace(/\@/g, "·−−·−· ");
    car = car.replace(/\_/g, "··−−·− ");
    car = car.replace(/\+/g, "·−·−· ");
    car = car.replace(/\=/g, "−···− ");
    car = car.replace(/0/g, "−−−−− ");
    car = car.replace(/1/g, "·−−−− ");
    car = car.replace(/2/g, "··−−− ");
    car = car.replace(/3/g, "···−− ");
    car = car.replace(/4/g, "····− ");
    car = car.replace(/5/g, "····· ");
    car = car.replace(/6/g, "−···· ");
    car = car.replace(/7/g, "−−··· ");
    car = car.replace(/8/g, "−−−·· ");
    car = car.replace(/9/g, "−−−−· ");
    car = car.replace(/A/g, "·− ");
    car = car.replace(/À/g, "·−−·− ");
    car = car.replace(/Ä/g, "·−·− ");
    car = car.replace(/B/g, "−··· ");
    car = car.replace(/C/g, "−·−· ");
    car = car.replace(/Ç/g, "−·−·· ");
    car = car.replace(/D/g, "−·· ");
    car = car.replace(/Ð/g, "−·−−· ");
    car = car.replace(/E/g, "· ");
    car = car.replace(/É/g, "··−·· ");
    car = car.replace(/È/g, "·−··− ");
    car = car.replace(/F/g, "··−· ");
    car = car.replace(/G/g, "−−· ");
    car = car.replace(/H/g, "···· ");
    car = car.replace(/I/g, "·· ");
    car = car.replace(/J/g, "·−−− ");
    car = car.replace(/K/g, "−·− ");
    car = car.replace(/L/g, "·−·· ");
    car = car.replace(/M/g, "−− ");
    car = car.replace(/N/g, "−· ");
    car = car.replace(/Ñ/g, "−−·−− ");
    car = car.replace(/O/g, "−−− ");
    car = car.replace(/Ö/g, "−−−· ");
    car = car.replace(/P/g, "·−−· ");
    car = car.replace(/Q/g, "−−·− ");
    car = car.replace(/R/g, "·−· ");
    car = car.replace(/S/g, "··· ");
    car = car.replace(/T/g, "− ");
    car = car.replace(/Þ/g, "·−−·· ");
    car = car.replace(/U/g, "··− ");
    car = car.replace(/Ü/g, "··−− ");
    car = car.replace(/V/g, "···− ");
    car = car.replace(/W/g, "·−− ");
    car = car.replace(/X/g, "−··− ");
    car = car.replace(/Y/g, "−·−− ");
    car = car.replace(/Z/g, "−−·· ");
    document.transcription.text2.value = car;
}

function cam() {
    ca = document.transcription.text2.value;
    ca = ca.replace(/\./g, "·");
    ca = ca.replace(/\;/g, "·");
    ca = ca.replace(/\*/g, "·");
    ca = ca.replace(/-/g, "−");
    ca = ca.replace(/_/g, "−");
    document.transcription.text2.value = ca;
}

function morlat() {
    car = document.transcription.text2.value;
    car = car.replace(/···−−−···/g, "SOS");

    car = car.replace(/····· /g, "5");
    car = car.replace(/−·−−· /g, "Ð");
    car = car.replace(/−····− /g, "-");
    car = car.replace(/····− /g, "4");
    car = car.replace(/··−−·· /g, "?");
    car = car.replace(/·−−·· /g, "Þ");
    car = car.replace(/··−·· /g, "É");
    car = car.replace(/·−··−· /g, "\"");
    car = car.replace(/·−··· /g, "&");
    car = car.replace(/−···· /g, "6");
    car = car.replace(/···· /g, "H");
    car = car.replace(/···−− /g, "3");
    car = car.replace(/··−−·− /g, "_");
    car = car.replace(/·−·−·− /g, ".");
    car = car.replace(/·−··− /g, "È");
    car = car.replace(/−···− /g, "=");
    car = car.replace(/···− /g, "V");
    car = car.replace(/·−−·−· /g, "@");
    car = car.replace(/−·−·−· /g, ";");
    car = car.replace(/·−·−· /g, "+");
    car = car.replace(/−··−· /g, "/");
    car = car.replace(/··−· /g, "F");
    car = car.replace(/−·−·· /g, "Ç");
    car = car.replace(/·−·· /g, "L");
    car = car.replace(/−−−··· /g, ":");
    car = car.replace(/−−··· /g, "7");
    car = car.replace(/−··· /g, "B");
    car = car.replace(/··· /g, "S");
    car = car.replace(/··−−− /g, "2");
    car = car.replace(/−·−·−− /g, "!");
    car = car.replace(/−−··−− /g, ",");
    car = car.replace(/··−− /g, "Ü");
    car = car.replace(/−·−−·− /g, ")");
    car = car.replace(/·−−·− /g, "À");
    car = car.replace(/·−·− /g, "Ä");
    car = car.replace(/−··− /g, "X");
    car = car.replace(/··− /g, "U");
    car = car.replace(/·−−−−· /g, "'");
    car = car.replace(/−·−−· /g, "(");
    car = car.replace(/·−−· /g, "P");
    car = car.replace(/−·−· /g, "C");
    car = car.replace(/·−· /g, "R");
    car = car.replace(/−−−·· /g, "8");
    car = car.replace(/−−·· /g, "Z");
    car = car.replace(/−·· /g, "D");
    car = car.replace(/·· /g, "I");
    car = car.replace(/·−−−− /g, "1");
    car = car.replace(/·−−− /g, "J");
    car = car.replace(/−−·−− /g, "Ñ");
    car = car.replace(/−·−− /g, "Y");
    car = car.replace(/·−− /g, "W");
    car = car.replace(/−−·− /g, "Q");
    car = car.replace(/−·− /g, "K");
    car = car.replace(/·− /g, "A");
    car = car.replace(/−−−−· /g, "9");
    car = car.replace(/−−−· /g, "Ö");
    car = car.replace(/−−· /g, "G");
    car = car.replace(/−· /g, "N");
    car = car.replace(/· /g, "E");
    car = car.replace(/−−−−− /g, "0");
    car = car.replace(/−−−− /g, "CH");
    car = car.replace(/−−− /g, "O");
    car = car.replace(/−− /g, "M");
    car = car.replace(/− /g, "T");

    car = car.replace(/·····/g, "5");
    car = car.replace(/−·−−·/g, "Ð");
    car = car.replace(/−····−/g, "-");
    car = car.replace(/····−/g, "4");
    car = car.replace(/··−−··/g, "?");
    car = car.replace(/·−−··/g, "Þ");
    car = car.replace(/··−··/g, "É");
    car = car.replace(/·−··−·/g, "\"");
    car = car.replace(/·−···/g, "&");
    car = car.replace(/−····/g, "6");
    car = car.replace(/····/g, "H");
    car = car.replace(/···−−/g, "3");
    car = car.replace(/··−−·−/g, "_");
    car = car.replace(/·−·−·−/g, ".");
    car = car.replace(/·−··−/g, "È");
    car = car.replace(/−···−/g, "=");
    car = car.replace(/···−/g, "V");
    car = car.replace(/·−−·−·/g, "@");
    car = car.replace(/−·−·−·/g, ";");
    car = car.replace(/·−·−·/g, "+");
    car = car.replace(/−··−·/g, "/");
    car = car.replace(/··−·/g, "F");
    car = car.replace(/−·−··/g, "Ç");
    car = car.replace(/·−··/g, "L");
    car = car.replace(/−−−···/g, ":");
    car = car.replace(/−−···/g, "7");
    car = car.replace(/−···/g, "B");
    car = car.replace(/···/g, "S");
    car = car.replace(/··−−−/g, "2");
    car = car.replace(/−·−·−−/g, "!");
    car = car.replace(/−−··−−/g, ",");
    car = car.replace(/··−−/g, "Ü");
    car = car.replace(/−·−−·−/g, ")");
    car = car.replace(/·−−·−/g, "À");
    car = car.replace(/·−·−/g, "Ä");
    car = car.replace(/−··−/g, "X");
    car = car.replace(/··−/g, "U");
    car = car.replace(/·−−−−·/g, "'");
    car = car.replace(/−·−−·/g, "(");
    car = car.replace(/·−−·/g, "P");
    car = car.replace(/−·−·/g, "C");
    car = car.replace(/·−·/g, "R");
    car = car.replace(/−−−··/g, "8");
    car = car.replace(/−−··/g, "Z");
    car = car.replace(/−··/g, "D");
    car = car.replace(/··/g, "I");
    car = car.replace(/·−−−−/g, "1");
    car = car.replace(/·−−−/g, "J");
    car = car.replace(/−−·−−/g, "Ñ");
    car = car.replace(/−·−−/g, "Y");
    car = car.replace(/·−−/g, "W");
    car = car.replace(/−−·−/g, "Q");
    car = car.replace(/−·−/g, "K");
    car = car.replace(/·−/g, "A");
    car = car.replace(/−−−−·/g, "9");
    car = car.replace(/−−−·/g, "Ö");
    car = car.replace(/−−·/g, "G");
    car = car.replace(/−·/g, "N");
    car = car.replace(/·/g, "E");
    car = car.replace(/−−−−−/g, "0");
    car = car.replace(/−−−−/g, "CH");
    car = car.replace(/−−−/g, "O");
    car = car.replace(/−−/g, "M");
    car = car.replace(/−/g, "T");
    car = car.replace(/\//g, " ");
    document.transcription.text1.value = car;
}

function alpha(item) {
    var input = document.forms['transcription'].elements['text2'];
    input.focus();
    if (typeof input.selectionStart !== undefined) {
        cursor = input.selectionStart;
        size = input.value.length;
        firstPart = input.value.substring(0, cursor);
        lastPart = input.value.substring(cursor, size);
        input.value = firstPart + item + lastPart;
        input.selectionStart += item.length;
    }
    else { // pour IE
        var range = document.selection.createRange();
        range.text = item;
    }
    input.focus();
    input.scrollTop = input.scrollHeight;
}
